### ISSUE TITLE
I cant not connect to LG TV i want to develop the remote control app.

### ISSUE THREAD

**Issue by vishalcears** [hobbyquaker/lgtv2#29]
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND lgwebostv lgwebostv:8000
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
    at WebSocketClient.<anonymous> (/var/www/html/lgtv2/node_modules/lgtv2/index.js:82:18)
    at WebSocketClient.emit (events.js:189:13)
    at ClientRequest.handleRequestError (/var/www/html/lgtv2/node_modules/websocket/lib/WebSocketClient.js:227:14)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by hobbyquaker** [comment]
`getaddrinfo ENOTFOUND lgwebostv` just means the default hostname does not resolve in your network - pass your TV: `new LGTV({host: '192.168.1.20'})` (1.8.0; or `url: 'wss://192.168.1.20:3001'`). The library now also tries the secure port first and falls back to 3000 for older TVs. Closing.
